import "./globals.css";
import Nav from "@/components/Nav";
import siteConfig from "@/site.config";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme={siteConfig.siteTheme}>
            <body>
                <Nav />
                {children}
            </body>
        </html>
    );
}
