import "./globals.css";
import Nav from "@/components/Nav";
import siteConfig from "@/site.config";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" data-theme={siteConfig.siteTheme}>
            <body>
                <Nav />
                {siteConfig.displayAnnouncement && (
                    <div className="bg-accent border-y py-6 px-4 overflow-x-hidden">
                        <div className="border w-screen text-4xl uppercase animate-marquee">
                            <span>{siteConfig.announcement}</span>
                            <span>{siteConfig.announcement}</span>
                            <span>{siteConfig.announcement}</span>
                            <span>{siteConfig.announcement}</span>
                            <span>{siteConfig.announcement}</span>
                        </div>
                    </div>
                )}
                {children}
            </body>
        </html>
    );
}
